### ISSUE TITLE
Oh my god, just learn CSS

### ISSUE THREAD

**Issue by smithtn3** [readmeio/petstore.dev#1]
https://github.com/readmeio/petstore.dev/blob/2315e2bc38e2ffef470434d94f3f3c5f31f0a0cb/styles/globals.css#L1

@gkoberger You should begin relearning CSS.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/70470334/198845466-acd0e789-6e07-42f5-8c8f-708143ba2a91.png">

**Comment by smithtn3** [comment]
@rafegoldberg On Monday, you should begin educating your boss about the dangers of these hazardous technologies.

There's technical debt all over the place.

**Comment by smithtn3** [comment]
cc @domharrington, @emilyskuo, @erunion, @gratcliff, @ilias-t, @kanadgupta, @mjcuva, @runnabro, @trishaprile

**Comment by erunion** [comment]
Unnecessary to tag all of us on this but thanks for the feedback!

**Comment by iMuzz** [comment]
@smithtn3 can you please tag me as well next time?
